### ISSUE TITLE
Backstage component

### ISSUE THREAD

**Issue by jeffmccune** [holos-run/holos#180]
References

- [Backstage UI](https://backstage.admin.aws2.holos.run/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=all)

Tasks

- [x] Backstage component
- [x] Holos IAM integration - 
- [x] `authpolicy-allow-portal`
- [x] [Configure GitHub Apps Integration](https://backstage.io/docs/integrations/github/github-apps)
- [x] [Configure GitHub Discovery](https://backstage.io/docs/integrations/github/discovery/#configuration)
- [x] ConfigMap for `/config/app-config.production.yaml`
- [x] Add a card for the holos-infra repo

Follow up tasks

- [x] #184
- [x] #185
- [x] #186
- [x] #188

## AuthorizationPolicy

```bash
kubectl get authorizationpolicies.security.istio.io -n istio-gateways authpolicy-allow-portal -o yaml | yq .spec
```

```yaml
action: ALLOW
rules:
  - to:
      - operation:
          hosts:
            - backstage.admin.aws2.holos.run
            - backstage.admin.aws2.holos.run:*
    when:
      - key: request.auth.principal
        values:
          - https://login.holos.run/*
      - key: request.auth.audiences
        values:
          - "269746002573969304"
      - key: request.auth.presenter
        values:
          - 269746420997801880@holos_platform
      - key: request.auth.claims[groups]
        values:
          - portal-view
selector:
  matchLabels:
    istio.io/gateway-name: default
```

## Github Integration

Refer to Backstage [Github Apps](https://backstage.io/docs/integrations/github/github-apps/) docs.
