### ISSUE TITLE
Common Labels

### ISSUE THREAD

**Issue by jeffmccune** [holos-run/holos#28]
Replace the idea of a holos project and our own custom labels with the following:

Want:

```yaml
app.kubernetes.io/name: secrets
app.kubernetes.io/instance: prod-secrets-eso
app.kubernetes.io/component: eso
app.kubernetes.io/part-of: prod
```

Have:

```cue
// #CommonLabels are mixed into every kubernetes api object.
#CommonLabels: {
	"holos.run/stage.name":     #InputKeys.stage
	"holos.run/project.name":   #InputKeys.project
	"holos.run/component.name": #InputKeys.component
	...
}
```

As part of this work add a kustomization.yaml file to add common labels when rendering the output for Flux.
