### ISSUE TITLE
Helm Values Merging

### ISSUE THREAD

**Issue by jeffmccune** [holos-run/holos#398]
Consider [Helm Hierarchies](https://medium.com/containers-101/using-helm-hierarchies-in-multi-source-argo-cd-applications-for-promoting-to-different-gitops-133c3bc93678)

To reduce the amount of work necessary to migrate from existing methodologies Holos should support taking a list of values files and passing them straight to `helm` like ArgoCD does.  We could still create each individual file from CUE if needed, but this support for merging would provide a migration path.

Similar to the Files and Resources fields of the Kustomize component kind.

```yaml
        valueFiles:
        - $values/my-values/common-values.yaml          
        - $values/my-values/app-version/prod-values.yaml               
        - $values/my-values/env-type/prod-values.yaml  
        - $values/my-values/regions/us-values.yaml                
        - $values/my-values/envs/prod-us-values.yaml
```

**Comment by jeffmccune** [comment]
Left off about to get holos render platform working in

https://github.com/holos-run/multi-sources-example

We are migrating https://github.com/holos-run/multi-sources-example/blob/v0.1.0/appsets/4-final/all-my-envs-appset-with-version.yaml

**Comment by jeffmccune** [comment]
This looks pretty straight forward to wire up as a `valueFiles` list on the Helm component kind.

See the `jeff/398-helm-values-merging` branch for the first implementation.

The purpose of adding this field is to provide a direct migration from an ApplicationSet without forcing users to refactor their values hierarchy.  Refactoring the values hierarchy can be difficult because it's unclear what values are actually used.  Providing a direct migration path turns `holo` into a tool that gives us clear insight into what values are actually used.

For example, in https://github.com/holos-run/multi-sources-example branch `jeff/values-hierarchy` at b2ebbcee062fefb1168ea780ef3ebe4ffa7b9836

    holos show buildplans --selector env=prod-us

```yaml
kind: BuildPlan
apiVersion: v1alpha5
metadata:
  name: my-chart
  labels:
    env: prod-us
    region: us
    type: prod
    version: prod
  annotations:
    app.holos.run/description: my-chart 0.1.0 for environment prod-us
spec:
  artifacts:
    - artifact: environments/prod-us/components/my-chart/my-chart.gen.yaml
      generators:
        - kind: Helm
          output: helm.gen.yaml
          helm:
            chart:
              name: my-chart
              version: 0.1.0
              release: my-chart
              repository:
                name: multi-sources-example
                url: https://kostis-codefresh.github.io/multi-sources-example
            values: {}
            valueFiles:
              - name: version-values.yaml
                kind: Values
                values:
                  imageVersion: "1.0"
              - name: type-values.yaml
                kind: Values
                values:
                  dbPassword: prod_password
                  dbUser: prod_username
                  environmentType: production
                  paypalUrl: production.paypal.com
              - name: region-values.yaml
                kind: Values
                values:
                  region: us
              - name: env-values.yaml
                kind: Values
                values:
                  cacheSize: 1024kb
                  environment: prod-us
                  gpuEnabled: "1"
                  nBuckets: "42"
                  pageLimit: "25"
                  replicaCount: 10
                  sorting: Ascending
                  userInterfaceTheme: dark
        - kind: Resources
          output: resources.gen.yaml
      transformers:
        - kind: Kustomize
          inputs:
            - helm.gen.yaml
            - resources.gen.yaml
          output: environments/prod-us/components/my-chart/my-chart.gen.yaml
          kustomize:
            kustomization:
              apiVersion: kustomize.config.k8s.io/v1beta1
              kind: Kustomization
              labels:
                - includeSelectors: false
                  pairs:
                    argocd.argoproj.io/instance: prod-us-my-chart
              namespace: prod-us
              resources:
                - helm.gen.yaml
                - resources.gen.yaml
    - artifact: gitops/prod-us-my-chart-application.gen.yaml
      generators:
        - kind: Resources
          output: gitops/prod-us-my-chart-application.gen.yaml
          resources:
            Application:
              prod-us-my-chart:
                apiVersion: argoproj.io/v1alpha1
                kind: Application
                metadata:
                  labels:
                    env: prod-us
                  name: prod-us-my-chart
                  namespace: argocd
                spec:
                  destination:
                    server: https://kubernetes.default.svc
                  project: default
                  source:
                    path: deploy/environments/prod-us/components/my-chart
                    repoURL: https://github.com/holos-run/multi-sources-example.git
                    targetRevision: main
```
